name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Zip Repository
        run: |
          zip -r lambda-code.zip .
        working-directory: .

      - name: Upload to S3
        run: |
          aws s3 cp lambda-code.zip s3://YourS3BucketName/path/to/lambda-code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy Infrastructure
        run: |
          aws cloudformation deploy \
            --template-file cloudformation-template.yml \
            --stack-name YourStackName \
            --capabilities CAPABILITY_IAM
            --parameter-overrides LambdaCodeS3Bucket=YourS3BucketName LambdaCodeS3Key=path/to/lambda-code.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
